# Generated by Django 5.0.4 on 2024-04-22 10:24

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0002_alter_products_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="price",
            new_name="preço",
        ),
        migrations.RemoveField(
            model_name="products",
            name="image",
        ),
        migrations.AddField(
            model_name="products",
            name="imagem",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                default="products/default.jpg",
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[700, 700],
                upload_to="products/",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="resumo",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="products",
            name="descrição",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="dominio",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
