# Generated by Django 5.0.4 on 2024-04-30 10:06

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0004_category_product_delete_products"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                default="products/default.jpg",
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[500, 500],
                upload_to="products/",
            ),
        ),
    ]
