from enum import Enum


class TokenType(Enum):
    OPEN_BRACE = "OPEN_BRACE"
    CLOSE_BRACE = "CLOSE_BRACE"
    OPEN_PAREN = "OPEN_PAREN"
    CLOSE_PAREN = "CLOSE_PAREN"
    SEMICOLON = "SEMICOLON"
    INT_KEYWORD = "INT_KEYWORD"
    RETURN_KEYWORD = "RETURN_KEYWORD"
    IDENTIFIER = "IDENTIFIER"
    INTEGER_LITERAL = "INTEGER_LITERAL"
