version: '3.3'

services:
  # app:
  #   container_name: gestao_vagas_app
  #   build:
  #     context: .

  #   tty: true
  #   depends_on:
  #     - postgres

  postgres:
    container_name: gestao_vagas_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_vagas


